// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkzsnrxunindwqttdzfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrenNucnh1bmluZHdxdHRkemZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDM3ODMsImV4cCI6MjA2ODkxOTc4M30.wMKZYNhIUW-rsSHVvy1Nnm_XervjiPlkNV7Q3mM0JJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});